---
- name: configure for controller ntp service
  copy: src=/etc/ansible/roles/ntp/files/controller-chrony.conf dest=/etc/chrony.conf owner=root group=root mode=0644

- name: restart ntp
  raw: systemctl start chronyd.service
# service: name=chrony state=restarted
