---
- name: create keystone database in MySQL Database
  command: mysql -uroot -e "create database {{ item }}";
  with_items:
   - nova
   

- name: give privileges on databases
  command: mysql -uroot -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'{{ item }}' IDENTIFIED BY 'KEYSTONE_DBPASS';"
  with_items:  item 
   - controller
   - localhost
