---
- name: mkdir mariadb dir under puppet dir
  file: path=/etc/puppet/mariadb state=touch

- name: mkdir files dir under mariadb
  file: path=/etc/puppet/modules/mariadb/files state=directory owner=root group=root mode=755

- name: mkdir manifests dir under mariadb
  file: path=/etc/puppet/modules/mariadb/manifests state=directory owner=root group=root mode=755
  
- name: copying configuration for mariadb
  copy: src=/etc/ansible/roles/mariadb/files/mariadb-server.cnf dest=/etc/puppet/modules/mariadb/files/mariadb-server.cnf owner=root group=root mode=644

- name: copying puppet pp file under manifest dir
  copy: src=/etc/ansible/roles/mariadb/files/init.pp dest=/etc/puppet/modules/mariadb/manifests/init.pp owner=root group=root mode=644 



